# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/gale/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),gale)

$(call add-radio-file-sha1-checked,radio/gz.img,6334b0931cc00473b7c321e3ee014db4317e0383)
$(call add-radio-file-sha1-checked,radio/lk.img,32ac14156e3cba32d7c59032f070b5682952897b)
$(call add-radio-file-sha1-checked,radio/logo.img,cbc137d090af2ac4b486a06c5a5fd01135b51180)
$(call add-radio-file-sha1-checked,radio/md1img.img,00de15497747dfa4b7dc2efeefb376a28660eefc)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,5384cf60e8a400518d6cb6f0b165bac869c2e78c)
$(call add-radio-file-sha1-checked,radio/scp.img,7d84f138d4bc060d3b784a96163a3763c6c3b5eb)
$(call add-radio-file-sha1-checked,radio/spmfw.img,c282e972b0054d608c803c70f07a060cdd060058)
$(call add-radio-file-sha1-checked,radio/sspm.img,4cc8a5c2557b048a2b23d84b2893db3e9c3a66e0)
$(call add-radio-file-sha1-checked,radio/tee.img,5ef5ad38d780cf0edfbdb6cf35d0c5e4d7e8426a)

endif
